addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: ac2396ea-9d49-4109-9919-b0eb5f4c6d22
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 360 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install: []
branches: ''
cache:
  directories:
  - $HOME/.m2
install:
- sh -c 'mvn install -DskipTests=true'
- sh -c 'cd jOOQ-examples/jOOQ-spring-example && mvn install -DskipTests=true'
- sh -c 'cd jOOQ-examples/jOOQ-spring-boot-example && mvn install -DskipTests=true'
- sh -c 'cd jOOQ-examples/jOOQ-flyway-example && mvn install -DskipTests=true'
- sh -c 'cd jOOQ-examples/jOOQ-nashorn-example && mvn install -DskipTests=true'
- sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn install -DskipTests=true'
- sh -c 'cd jOOQ-examples/jOOQ-codegen-gradle && gradle build'
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-stg.public-swarm.devfactory.com/travisWebHookListener?build_id=ac2396ea-9d49-4109-9919-b0eb5f4c6d22
script:
- sh -c 'mvn test'
- sh -c 'cd jOOQ-examples/jOOQ-spring-example && mvn test'
- sh -c 'cd jOOQ-examples/jOOQ-spring-boot-example && mvn test'
- sh -c 'cd jOOQ-examples/jOOQ-flyway-example && mvn test'
- sh -c 'cd jOOQ-examples/jOOQ-nashorn-example && mvn test'
- sh -c 'cd jOOQ-examples/jOOQ-spring-guice-example && mvn test'
# Modified by Insights Service at 2016-11-11 19:26:15.094634
